<a href="https://colab.research.google.com/github/Mokshith2592/NN/blob/main/imageClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
(X_train ,y_train) ,(X_test ,y_test) = tf.keras.datasets.cifar10.load_data()

170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 4s 0us/step


In [ ]:
X_train.shape
y_train.shape

(50000, 1)

In [ ]:
classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]
classes[y_train[5][0]]

'automobile'

In [ ]:
# scaling down to 0-1
X_train_scaled = X_train/255
X_test_scaled = X_test/255

In [ ]:
y_train_categorical = keras.utils.to_categorical(
    y_train, num_classes=10
)
y_test_categorical = keras.utils.to_categorical(
    y_test, num_classes=10
)

print(y_train[0:5])
print(y_train_categorical[0:5])

# This is called one-hot encoding

[[6]
 [9]
 [9]
 [4]
 [1]]
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(32 ,32 ,3)),
    keras.layers.Dense(3000 ,activation="relu"),
    keras.layers.Dense(1000 ,activation="relu"),
    keras.layers.Dense(10 ,activation="sigmoid")
])

model.compile(optimizer='SGD',
            loss='categorical_crossentropy',
            metrics=['accuracy'])

model.fit(X_train_scaled ,y_train_categorical ,epochs=50)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 132s 84ms/step - accuracy: 0.3039 - loss: 1.9301
Epoch 2/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 139s 82ms/step - accuracy: 0.4195 - loss: 1.6466
Epoch 3/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 132s 85ms/step - accuracy: 0.4545 - loss: 1.5482
Epoch 4/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 143s 85ms/step - accuracy: 0.4732 - loss: 1.4922
Epoch 5/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 144s 87ms/step - accuracy: 0.4977 - loss: 1.4351
Epoch 6/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 131s 84ms/step - accuracy: 0.5074 - loss: 1.3949
Epoch 7/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 135s 86ms/step - accuracy: 0.5265 - loss: 1.3502
Epoch 8/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 129s 83ms/step - accuracy: 0.5374 - loss: 1.3122
Epoch 9/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 157s 92ms/step - accuracy: 0.5478 - loss: 1.2814
Epoch 10/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 188s 83ms/step - accuracy: 0.5614 - loss: 1.2485
Epoch 11/50
1563/1563 ━━━━━━━━━━━━━━━━━━━━ 127s 81ms/step - accuracy: 0.5768 - loss: 1.21

In [ ]:
model.predict()